# Generated by Django 4.0.4 on 2022-04-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='title')),
                ('desc', models.TextField(verbose_name='description')),
                ('views_count', models.IntegerField(default=0, verbose_name='views count')),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies', verbose_name='image')),
                ('category', models.CharField(choices=[('A', 'ACTION'), ('D', 'DRAMA'), ('C', 'COMEDY'), ('R', 'ROMANCE')], max_length=10, verbose_name='category')),
                ('langauge', models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMANY')], max_length=10, verbose_name='language')),
                ('year_of_production', models.DateField(auto_now_add=True, verbose_name='year of production')),
                ('status', models.CharField(choices=[('MW', 'MOST WATCHED'), ('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED')], max_length=10, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
