# Generated by Django 4.0.4 on 2022-04-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieImdb', '0002_alter_movie_year_of_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default=1, max_length=350, verbose_name='cast'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=50, verbose_name='type')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='movieImdb.movie', verbose_name='movie')),
            ],
            options={
                'verbose_name': 'MovieLink',
                'verbose_name_plural': 'MovieLinks',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
