# Generated by Django 4.0.4 on 2022-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieImdb', '0003_movie_cast_movielink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielink',
            options={'verbose_name': 'MovieLink', 'verbose_name_plural': 'MovieLinks'},
        ),
        migrations.AddField(
            model_name='movielink',
            name='link',
            field=models.URLField(default=1, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='movielink',
            table=None,
        ),
    ]
