# Generated by Django 4.0.4 on 2022-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieImdb', '0005_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='type',
            field=models.CharField(choices=[('download link', 'DOWNLOAD LINK'), ('watch link', 'WATCH LINK')], max_length=50, verbose_name='type'),
        ),
    ]
