# Generated by Django 4.0.4 on 2022-04-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieImdb', '0006_alter_movielink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='langauge',
            field=models.CharField(choices=[('english', 'ENGLISH'), ('germany', 'GERMANY')], max_length=30, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('most watched', 'MOST WATCHED'), ('recently added', 'RECENTLY ADDED'), ('top rated', 'TOP RATED')], max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='movielink',
            name='type',
            field=models.CharField(choices=[('D', 'DOWNLOAD LINK'), ('W', 'WATCH LINK')], max_length=50, verbose_name='type'),
        ),
    ]
